Repository FC-final-project-team7/just-try-eat-ai-video-FE, pull requests merged in 2022-10, with the labels that each got.

#64 #11 feat: Create Modal
  src/assets/icons/close.svg
  src/assets/icons/cloud.svg
  src/assets/icons/text.svg
  src/components/Popup/ConfirmModal/index.tsx
  src/components/Popup/ConfirmModal/style.ts
  src/components/Popup/NoticeModal/index.tsx
  src/components/Popup/NoticePopup/index.tsx
  src/components/Popup/ProjectSelectModal/index.tsx
  src/components/Popup/ProjectSelectModal/style.ts
  src/pages/ProjectListPage/Card/ProjectCard/index.tsx
  src/pages/ProjectListPage/Card/VideoCard/index.tsx
  src/pages/ProjectListPage/ListContainer/ProjectList/index.tsx
  src/pages/ProjectListPage/ListContainer/ProjectList/style.ts
  src/pages/ProjectListPage/ListContainer/VideoList/style.ts
  src/styles/GlobalStyle.tsx
Labels: Priority: Critical, Type: Enhancement

#60 #26 feat: Create selected avatar preview
  package-lock.json
  src/pages/SelectAvatarPage/SelectAvatarList/index.tsx
  src/pages/SelectAvatarPage/SelectedAvatarPreview/index.tsx
  src/pages/SelectAvatarPage/SelectedAvatarPreview/style.ts
  src/pages/SelectAvatarPage/TabMenuList/index.tsx
  src/pages/SelectAvatarPage/index.tsx
  src/pages/index.jsx
  src/pages/pages.ts
  yarn.lock
Labels: Priority: High, Type: Enhancement

#61 [feat]: Create related directories and Connected files
  package-lock.json
  src/pages/SelectAvatarPage/SelectAvatarList/index.tsx
  src/pages/SelectAvatarPage/SelectedAvatarPreview/index.tsx
  src/pages/SelectAvatarPage/TabMenuList/index.tsx
  src/pages/SelectAvatarPage/index.tsx
  src/pages/index.jsx
  src/pages/pages.ts
  yarn.lock
Labels: Priority: High, Type: Enhancement

#66 #12 refactor: Using grid
  .idea/compiler.xml
  .idea/jsLinters/eslint.xml
  .idea/prettier.xml
  src/pages/ProjectText/ProjectTextarea/index.tsx
  src/pages/ProjectText/ProjectVoiceOptions/Slider/index.tsx
  src/pages/ProjectText/ProjectVoiceOptions/index.tsx
  src/pages/ProjectText/ProjectVoiceOptions/styles.tsx
  src/pages/ProjectText/ProjectVoiceSelect/index.tsx
  src/pages/ProjectText/index.tsx
  src/pages/ProjectText/mixin.ts
  src/pages/ProjectText/styles.tsx
  src/utils/number.ts
Labels: Priority: Medium, Type: Maintenance

#67 #11 feat: Create Popup
  src/assets/icons/error-close.svg
  src/assets/icons/error.svg
  src/components/Popup/ConfirmModal/index.tsx
  src/components/Popup/ConfirmModal/style.ts
  src/components/Popup/ErrorModal/index.tsx
  src/components/Popup/Loaders/BaseLoader.tsx
  src/components/Popup/NoticeModal/index.tsx
  src/components/Popup/ProjectSelectModal/index.tsx
  src/components/Popup/ProjectSelectModal/style.ts
  src/components/Popup/VideoDownloadModal/index.tsx
  src/components/Popup/hooks.ts
  src/pages/ProjectListPage/Card/ProjectCard/style.ts
  src/pages/ProjectListPage/Card/VideoCard/index.tsx
  src/pages/ProjectListPage/Card/VideoCard/style.ts
  src/pages/ProjectListPage/ListContainer/ProjectList/index.tsx
  src/pages/ProjectListPage/data.ts
  src/styles/theme.ts
Labels: Priority: Critical, Type: Enhancement

#68 #11 feat: Create Popup #67
  src/assets/icons/error-big.svg
  src/components/Popup/ErrorModal/FetchErrorModal.tsx
  src/components/Popup/ErrorModal/UploadErrorModal.tsx
  src/components/Popup/Loaders/Loader.tsx
  src/components/Popup/Loaders/OverlayLoader.tsx/index.tsx
  src/pages/ProjectListPage/Card/VideoCard/index.tsx
  src/pages/ProjectListPage/ListContainer/ProjectList/index.tsx
Labels: Priority: Critical, Type: Enhancement

#69 #33 feat: Update ProjectListContainer
  src/pages/ProjectListPage/Card/VideoCard/index.tsx
  src/pages/ProjectListPage/ListContainer/ProjectList/index.tsx
  src/pages/ProjectListPage/ListContainer/ProjectList/style.ts
  src/pages/ProjectListPage/ListContainer/VideoList/index.tsx
  src/pages/ProjectListPage/ListContainer/VideoList/style.ts
Labels: Priority: High, Type: Enhancement

#72 #35 feat: Create GNB
  src/assets/icons/dropdown-down.svg
  src/assets/icons/dropdown-up.svg
  src/assets/icons/logo.svg
  src/assets/icons/profile.svg
  src/components/GNB/Dropdown/index.tsx
  src/components/GNB/TitleInput/index.tsx
  src/components/GNB/index.tsx
  src/components/GNB/style.ts
  src/pages/index.jsx
  src/pages/pages.ts
Labels: Priority: Critical, Type: Enhancement

#73 #71 feat: Create Login API
  package.json
  src/pages/Login/index.tsx
  src/stores/apis/auth.ts
  src/stores/apis/baseQuery.ts
  src/stores/apis/index.ts
  src/stores/apis/projectText.ts
  src/stores/index.tsx
  src/stores/token.ts
  src/types/auth.ts
  src/utils/ObjectEx.ts
  yarn.lock
Labels: Priority: Critical, Type: Enhancement

#75 #74 feat: Create Project List API
  src/pages/ProjectListPage/Card/ProjectCard/index.tsx
  src/pages/ProjectListPage/ListContainer/ProjectList/index.tsx
  src/pages/ProjectListPage/ListContainer/VideoList/index.tsx
  src/pages/ProjectListPage/index.tsx
  src/stores/apis/projectList.ts
  src/stores/apis/videoList.ts
  src/types/projects.ts
Labels: Priority: High, Type: Enhancement

#77 conf: Apply Proxy Server
  netlify.toml
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers/data.ts
  src/mocks/handlers/index.ts
  src/mocks/handlers/projectText.ts
  src/mocks/handlers/utils.ts
  src/pages/Login/index.tsx
  src/stores/apis/auth.ts
  src/stores/apis/baseQuery.ts
  src/stores/apis/projectText.ts
  src/stores/apis/projects.ts
  src/types/project/projects.ts
  vite.config.ts
  yarn.lock
Labels: Priority: Critical, Type: Maintenance

#79 #33 feat: Update Project List
  src/pages/ProjectListPage/Card/ProjectCard/index.tsx
  src/pages/ProjectListPage/ListContainer/ProjectList/index.tsx
  src/stores/apis/videoList.ts
  src/types/projects.ts
Labels: Priority: High, Type: Enhancement

#80 #9 refactor: Add memo
  src/components/Buttons/BaseButton.tsx
  src/components/Buttons/FilledButton/index.tsx
  src/components/Buttons/ImageButton/index.tsx
  src/components/Buttons/OutlinedButton/index.tsx
Labels: Priority: Low, Type: Maintenance

#81 #16 feat: Add mixin
  src/pages/ProjectText/ProjectTextarea/index.tsx
  src/pages/ProjectText/index.tsx
  src/styles/mixins.ts
Labels: Priority: High, Type: Maintenance

#82 rename: Move projects types
  src/pages/ProjectListPage/Card/ProjectCard/index.tsx
  src/stores/apis/projectList.ts
  src/types/project/projects.ts
  src/types/project/voices.ts
Labels: Priority: Low, Type: Maintenance

#83 feat: Apply Suspense
  src/hooks/useRtkQueryResource.ts
  src/pages/ProjectText/index.tsx
  src/pages/ProjectText/styles.tsx
Labels: Priority: Medium, Type: Enhancement

#84 #12 feat: Add translate
  src/hooks/useTranslate.ts
  src/pages/ProjectText/translate/hooks.ts
  src/pages/ProjectText/translate/index.ts
  src/pages/ProjectText/translate/ko.ts
  src/pages/ProjectText/translate/mapper.ts
  src/types/objectPath.ts
  src/utils/ObjectEx.ts
Labels: Priority: Medium, Type: Enhancement

#85 #17 #18 refactor: Apply translate and CleanUp
  src/pages/ProjectText/ProjectVoiceOptions/Slider/index.tsx
  src/pages/ProjectText/ProjectVoiceOptions/constants.tsx
  src/pages/ProjectText/ProjectVoiceOptions/index.tsx
  src/pages/ProjectText/ProjectVoiceOptions/styles.tsx
  src/pages/ProjectText/components/Label.tsx
  src/pages/ProjectText/index.tsx
  src/pages/ProjectText/styles.tsx
  src/utils/WithApplyStyledSVG.tsx
Labels: Priority: Medium, Type: Maintenance

#86 #17 #18 fix: Wrong use useTranslate
  src/pages/ProjectText/ProjectVoiceOptions/Slider/index.tsx
Labels: Priority: Critical, Type: Bug

#87 #21 feat: Create SentenceInterval
  src/assets/icons/minus-bold.svg
  src/assets/icons/plus-bold.svg
  src/pages/ProjectText/ProjectVoiceOptions/SentenceInterval/commands.tsx
  src/pages/ProjectText/ProjectVoiceOptions/SentenceInterval/index.tsx
  src/pages/ProjectText/ProjectVoiceOptions/SentenceInterval/styles.tsx
  src/pages/ProjectText/ProjectVoiceOptions/index.tsx
  src/pages/ProjectText/components/IconButton.tsx
  src/utils/makeDefaultProps.ts
Labels: Priority: Critical, Type: Enhancement

#89 #74 feat: Update Main page
  src/assets/images/hexagon-1.png
  src/assets/images/hexagon-2.png
  src/assets/images/hexagon-3.png
  src/assets/images/hexagon-4.png
  src/assets/images/hexagon-5.png
  src/assets/images/hexagon-6.png
  src/assets/images/hexagon-7.png
  src/assets/images/partners.png
  src/pages/Main/index.tsx
  src/pages/Main/style.ts
Labels: Priority: High

#90 fix: Remove error
  index.html
  package.json
  public/mockServiceWorker.js
  src/main.tsx
  src/styles/GlobalStyle.tsx
Labels: Priority: High, Type: Maintenance

#91 feat!: Add styled-components-fast
  package.json
  src/components/Buttons/BaseButton.tsx
  src/components/Buttons/FilledButton/index.tsx
  src/components/Buttons/OutlinedButton/index.tsx
  src/components/GNB/Dropdown/index.tsx
  src/components/GNB/TitleInput/index.tsx
  src/components/GNB/style.ts
  src/components/Popup/ConfirmModal/style.ts
  src/components/Popup/ErrorModal/FetchErrorModal.tsx
  src/components/Popup/ErrorModal/UploadErrorModal.tsx
  src/components/Popup/Loaders/Loader.tsx
  src/components/Popup/Loaders/OverlayLoader.tsx/index.tsx
  src/components/Popup/NoticeModal/index.tsx
  src/components/Popup/ProjectSelectModal/style.ts
  src/components/Popup/VideoDownloadModal/index.tsx
  src/pages/ComponentsDisplay/Buttons/index.tsx
  src/pages/Main/style.ts
  src/pages/ProjectListPage/Card/ProjectCard/style.ts
  src/pages/ProjectListPage/Card/VideoCard/style.ts
  src/pages/ProjectListPage/ListContainer/ProjectList/style.ts
  src/pages/ProjectListPage/ListContainer/VideoList/style.ts
  src/pages/ProjectListPage/index.tsx
  src/pages/ProjectText/ProjectTextarea/index.tsx
  src/pages/ProjectText/ProjectVoiceOptions/SentenceInterval/styles.tsx
  src/pages/ProjectText/ProjectVoiceOptions/Slider/styles.tsx
  src/pages/ProjectText/ProjectVoiceOptions/styles.tsx
  src/pages/ProjectText/ProjectVoiceSelect/AvatarVoiceItem/styles.ts
  src/pages/ProjectText/ProjectVoiceSelect/AvatarVoiceLangSelect/styles.ts
  src/pages/ProjectText/ProjectVoiceSelect/AvatarVoiceSexRadioButtons/styles.ts
  src/pages/ProjectText/ProjectVoiceSelect/styles.ts
  src/pages/ProjectText/components/IconButton.tsx
  src/pages/ProjectText/components/Label.tsx
  src/pages/ProjectText/mixin.ts
  src/pages/ProjectText/styles.tsx
  src/pages/SelectAvatarPage/SelectAvatarList/Slide/style.ts
  src/pages/SelectAvatarPage/SelectAvatarList/style.ts
  src/pages/SelectAvatarPage/SelectedAvatarPreview/style.ts
  src/pages/SelectAvatarPage/TabMenuList/style.ts
  src/pages/SelectAvatarPage/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/mixins.ts
  src/styles/reset.ts
  src/styles/types.d.ts
  src/utils/WithApplyStyledSVG.tsx
  src/utils/styled-components-fast.ts
  yarn.lock
Labels: Priority: High, Type: Maintenance

#92 #30 #33 feat: Apply Project API
  src/components/Popup/ConfirmModal/index.tsx
  src/components/Popup/ErrorModal/UploadErrorModal.tsx
  src/components/Popup/ProjectSelectModal/index.tsx
  src/pages/ProjectListPage/Card/ProjectCard/index.tsx
  src/pages/ProjectListPage/Card/ProjectCard/style.ts
  src/pages/ProjectListPage/ListContainer/ProjectList/index.tsx
  src/pages/SelectAvatarPage/TabMenuList/TabComponents/TabClosetOne.tsx
  src/pages/SelectAvatarPage/TabMenuList/TabComponents/TabClosetThree.tsx
  src/pages/pages.ts
  src/stores/apis/index.ts
  src/stores/apis/projectCreation.ts
  src/stores/apis/projectList.ts
  src/stores/apis/tags.ts
Labels: Priority: Critical, Type: Enhancement

#93 #30 #33 feat: Update Project API and Add Loader
  src/pages/ProjectListPage/ListContainer/ProjectList/index.tsx
  src/pages/ProjectListPage/ListContainer/ProjectList/style.ts
  src/pages/ProjectListPage/ListContainer/VideoList/index.tsx
  src/pages/ProjectListPage/ListContainer/VideoList/style.ts
  src/stores/apis/projectList.ts
  src/stores/apis/videoList.ts
Labels: Priority: High, Type: Enhancement

#94 #12 refactor: Apply Server data and mappers
  src/assets/icons/play.svg
  src/mocks/handlers/data.ts
  src/mocks/handlers/projectText.ts
  src/pages/ProjectText/ProjectVoiceOptions/SentenceInterval/index.tsx
  src/pages/ProjectText/ProjectVoiceOptions/SentenceInterval/styles.tsx
  src/pages/ProjectText/ProjectVoiceOptions/Slider/styles.tsx
  src/pages/ProjectText/ProjectVoiceOptions/constants.tsx
  src/pages/ProjectText/ProjectVoiceOptions/index.tsx
  src/pages/ProjectText/ProjectVoiceSelect/AvatarVoiceItem/index.tsx
  src/pages/ProjectText/ProjectVoiceSelect/constants.ts
  src/pages/ProjectText/ProjectVoiceSelect/index.tsx
  src/pages/ProjectText/components/StyledSVG.tsx
  src/pages/ProjectText/index.tsx
  src/pages/ProjectText/styles.tsx
  src/pages/ProjectText/translate/ko.ts
  src/stores/apis/baseQuery.ts
  src/stores/apis/projectText.ts
  src/stores/apis/projects.ts
  src/types/project/projects.ts
  src/types/project/voices.ts
  src/utils/ObjectEx.ts
Labels: Priority: Critical, Type: Bug, Type: Maintenance

#95 conf: Bump packgase
  package.json
  yarn.lock
Labels: Priority: Low, Type: Maintenance

#96 #12 fix: Show ProjectText with wrong server data
  src/components/Popup/ProjectSelectModal/index.tsx
  src/pages/ProjectText/ProjectVoiceSelect/index.tsx
  src/stores/apis/projectCreation.ts
Labels: Priority: Critical, Type: Bug

#97 feat: Follow selected avatarAudio
  src/pages/ProjectText/ProjectVoiceSelect/constants.ts
  src/pages/ProjectText/ProjectVoiceSelect/hooks.ts
  src/pages/ProjectText/ProjectVoiceSelect/index.tsx
  src/pages/ProjectText/index.tsx
Labels: Priority: Medium, Type: Enhancement

#105 #11 feat: Add navigate and Loader in ProjectCreateModal
  src/components/Popup/ProjectCreateModal/index.tsx
  src/components/Popup/ProjectCreateModal/style.ts
  src/pages/ProjectListPage/ListContainer/ProjectList/index.tsx
Labels: Priority: High, Type: Enhancement

#106 #12 feat: Add Temp Buttons
  src/pages/ProjectText/index.tsx
  src/pages/ProjectText/styles.tsx
  src/stores/apis/auth.ts
  src/stores/apis/projectText.ts
  src/types/project/projects.ts
Labels: Priority: Medium, Type: Enhancement

#107 #12 refactor: Split types
  src/main.tsx
  src/pages/ProjectText/index.tsx
  src/stores/apis/projectText.ts
  src/types/project/projects.ts
  src/types/project/sentence.ts
Labels: Priority: Low, Type: Maintenance

#108 #100 feat: Create Sentence API
  src/mocks/handlers/data.ts
  src/stores/apis/projectSentence.ts
  src/types/project/projects.ts
  src/types/project/sentence.ts
Labels: Priority: Critical, Type: Enhancement

#109 #98 feat: Create ProjectSentencePage
  src/pages/ProjectSentence/index.tsx
  src/pages/index.jsx
Labels: Priority: Critical, Type: Enhancement

#110 #12 design: Apply OverlayLoader
  src/pages/ProjectText/index.tsx
Labels: Priority: Critical, Type: Enhancement

#111 #11 design: Modify positions in OverlayLoader
  src/components/Popup/Loaders/OverlayLoader.tsx/index.tsx
Labels: Priority: Medium

#113 feat: Add ErrorBoundary
  src/components/ErrorBoundary/index.tsx
  src/hooks/useRtkQueryResource.ts
  src/pages/index.jsx
Labels: Priority: Critical, Type: Enhancement

#114 retactor: Extrance ProjectTextarea
  src/components/Project/ProjectTextarea/index.tsx
  src/pages/ProjectText/ProjectVoiceOptions/styles.tsx
  src/pages/ProjectText/ProjectVoiceSelect/styles.ts
  src/pages/ProjectText/mixin.ts
  src/pages/ProjectText/styles.tsx
  src/styles/mixins.ts
Labels: Priority: High, Type: Maintenance

#115 #101 feat: Create sentence Textarea
  src/components/ErrorBoundary/index.tsx
  src/mocks/handlers/data.ts
  src/pages/ProjectSentence/ProjectStepper/index.tsx
  src/pages/ProjectSentence/index.tsx
  src/pages/ProjectSentence/styles.ts
  src/types/project/sentence.ts
Labels: Priority: Critical, Type: Enhancement

#116 #112 feat: Create footer
  src/assets/icons/logo-footer.svg
  src/assets/images/footer-link-home.png
  src/assets/images/footer-link-team.png
  src/assets/images/footer-link-youtube.png
  src/components/Footer/index.tsx
  src/components/Footer/style.ts
  src/components/StyleLayout/index.tsx
  src/pages/index.jsx
Labels: Priority: High, Type: Enhancement

#117 feat: Extract Slider
  src/components/Project/Slider/index.tsx
  src/components/Project/Slider/styles.tsx
  src/hooks/useTranslate.ts
  src/pages/ProjectText/ProjectVoiceOptions/index.tsx
  src/pages/ProjectText/ProjectVoiceOptions/styles.tsx
Labels: Priority: High, Type: Enhancement, Type: Maintenance

#119 #35 feat: Apply useProjectId in GNB
  src/components/GNB/index.tsx
  src/components/StyleLayout/index.tsx
  src/hooks/useProjectId.ts
  src/pages/index.jsx
  src/pages/pages.ts
Labels: Priority: High, Type: Enhancement

#122 #121 feat: Create NotFound page
  src/pages/NotFound/index.tsx
  src/pages/index.jsx
Labels: Priority: Medium, Type: Enhancement

#124 #19 fix: Hide scroll-x
  src/styles/GlobalStyle.tsx
Labels: Priority: Critical, Type: Bug

#127 #35 feat: Apply has tokens in login button
  src/components/GNB/index.tsx
  src/stores/token.ts
Labels: Priority: High, Type: Enhancement

#128 conf: Apply styled-components beta
  package.json
  src/App.tsx
  src/components/Buttons/BaseButton.tsx
  src/components/Buttons/FilledButton/index.tsx
  src/components/Buttons/OutlinedButton/index.tsx
  src/components/Footer/style.ts
  src/components/GNB/Dropdown/index.tsx
  src/components/GNB/TitleInput/index.tsx
  src/components/GNB/style.ts
  src/components/Popup/ConfirmModal/style.ts
  src/components/Popup/ErrorModal/FetchErrorModal.tsx
  src/components/Popup/ErrorModal/UploadErrorModal.tsx
  src/components/Popup/Loaders/Loader.tsx
  src/components/Popup/Loaders/OverlayLoader.tsx/index.tsx
  src/components/Popup/NoticeModal/index.tsx
  src/components/Popup/ProjectCreateModal/style.ts
  src/components/Popup/VideoDownloadModal/index.tsx
  src/components/Project/ProjectTextarea/index.tsx
  src/components/Project/Slider/styles.tsx
  src/pages/ComponentsDisplay/Buttons/index.tsx
  src/pages/Main/style.ts
  src/pages/NotFound/index.tsx
  src/pages/ProjectListPage/Card/ProjectCard/style.ts
  src/pages/ProjectListPage/Card/VideoCard/style.ts
  src/pages/ProjectListPage/ListContainer/ProjectList/style.ts
  src/pages/ProjectListPage/ListContainer/VideoList/style.ts
  src/pages/ProjectListPage/index.tsx
  src/pages/ProjectSentence/Prelisten/styles.ts
  src/pages/ProjectSentence/styles.ts
  src/pages/ProjectText/ProjectVoiceOptions/SentenceInterval/styles.tsx
  src/pages/ProjectText/ProjectVoiceOptions/styles.tsx
  src/pages/ProjectText/ProjectVoiceSelect/AvatarVoiceItem/styles.ts
  src/pages/ProjectText/ProjectVoiceSelect/AvatarVoiceLangSelect/styles.ts
  src/pages/ProjectText/ProjectVoiceSelect/AvatarVoiceSexRadioButtons/styles.ts
  src/pages/ProjectText/ProjectVoiceSelect/styles.ts
  src/pages/ProjectText/components/IconButton.tsx
  src/pages/ProjectText/components/Label.tsx
  src/pages/ProjectText/components/StyledSVG.tsx
  src/pages/ProjectText/styles.tsx
  src/pages/SelectAvatarPage/SelectAvatarList/Slide/style.ts
  src/pages/SelectAvatarPage/SelectAvatarList/style.ts
  src/pages/SelectAvatarPage/SelectedAvatarPreview/style.ts
  src/pages/SelectAvatarPage/TabMenuList/style.ts
  src/pages/SelectAvatarPage/index.tsx
  src/styles/GlobalStyle.tsx
  src/styles/mixins.ts
  src/styles/reset.ts
  src/styles/types.d.ts
  src/utils/WithApplyStyledSVG.tsx
  src/utils/styled-components-fast.ts
  yarn.lock
Labels: Priority: Low, Type: Maintenance

#129 #71 feat: Update login page style
  package.json
  src/assets/icons/google.svg
  src/assets/icons/logo-login.svg
  src/assets/icons/naver.svg
  src/pages/Login/index.tsx
  src/pages/Login/style.ts
  yarn.lock
Labels: Priority: High, Type: Enhancement

#130 style: Restore logo & service name
  src/components/Footer/index.tsx
  src/components/GNB/index.tsx
  src/pages/Main/index.tsx
Labels: Priority: Low

#132 #131 feat: Create RequireAuth page
  src/pages/RequireAuth/index.tsx
  src/pages/index.jsx
Labels: Priority: Critical, Type: Enhancement

#133 #104 feat: Generate Sentences
  src/components/ErrorBoundary/index.tsx
  src/components/Project/Slider/index.tsx
  src/hooks/useAudio.ts
  src/hooks/useTranslate.ts
  src/pages/ProjectSentence/EditSentence/index.tsx
  src/pages/ProjectSentence/EditSentence/itemStyles.tsx
  src/pages/ProjectSentence/EditSentence/styles.ts
  src/pages/ProjectSentence/Prelisten/hooks.tsx
  src/pages/ProjectSentence/Prelisten/index.tsx
  src/pages/ProjectSentence/fakeData.json
  src/pages/ProjectSentence/index.tsx
  src/pages/ProjectSentence/styles.ts
  src/pages/ProjectSentence/translate/ko.ts
  src/pages/ProjectText/ProjectVoiceOptions/index.tsx
  src/pages/ProjectText/index.tsx
  src/pages/index.jsx
  src/stores/apis/projectSentence.ts
  src/stores/apis/projectText.ts
  src/stores/apis/projects.ts
  src/styles/GlobalStyle.tsx
  src/types/project/projects.ts
  src/types/project/sentence.ts
  src/utils/ObjectEx.ts
Labels: Priority: Critical, Type: Enhancement

#134 chore: Add hide button
  src/components/Footer/style.ts
  src/components/GNB/index.tsx
Labels: Priority: Low

#135 design: Apply contents margin
  src/components/Project/ProjectStepper/index.tsx
  src/pages/ProjectSentence/ProjectStepper/index.tsx
  src/pages/ProjectSentence/index.tsx
  src/pages/ProjectSentence/styles.ts
  src/pages/ProjectText/ProjectTextStepper/index.tsx
  src/pages/ProjectText/index.tsx
  src/pages/ProjectText/styles.tsx
Labels: Priority: Medium, Type: Maintenance

#136 #71 feat: Update login onSubmitHandler
  src/pages/Login/index.tsx
Labels: Priority: High, Type: Maintenance

#137 #98 design: Apply Loader
  src/components/Popup/Loaders/OverlayLoader/index.tsx
  src/pages/ProjectSentence/index.tsx
  src/pages/ProjectText/index.tsx
Labels: Priority: High, Type: Enhancement

#138 #35 feat: Add ListButton in sentence page
  src/components/GNB/index.tsx
Labels: Priority: Low

#139 refactor: Optimize useTranslate
  .husky/pre-commit
  .idea/jsLibraryMappings.xml
  .idea/jsLinters/eslint.xml
  package.json
  src/components/Buttons/ImageButton/index.tsx
  src/hooks/useAudio.ts
  src/hooks/useProjectId.ts
  src/hooks/useTranslate.ts
  src/types/objectPath.ts
  src/types/svgr.d.ts
  src/types/types.d.ts
  src/types/types.ts
  src/utils/WithApplyStyledSVG.tsx
  yarn.lock
Labels: Priority: Medium, Type: Maintenance

#140 fix: Clean Up
  src/hooks/useTranslate.ts
  src/types/objectPath.ts
Labels: Priority: Critical, Type: Maintenance

#145 #144 feat: Create pages related to membership
  src/assets/icons/check.svg
  src/assets/icons/checkbox-active.svg
  src/assets/icons/checkbox.svg
  src/assets/images/signup-line-1.svg
  src/assets/images/signup-line-2.svg
  src/components/FormInput/index.tsx
  src/components/FormInput/style.ts
  src/components/Heading/index.tsx
  src/components/StyleLayout/index.tsx
  src/pages/SignUp/Completed/index.tsx
  src/pages/SignUp/Info/index.tsx
  src/pages/SignUp/Info/style.ts
  src/pages/SignUp/Stepper/index.tsx
  src/pages/SignUp/Stepper/style.ts
  src/pages/SignUp/index.tsx
  src/pages/SignUp/style.ts
  src/pages/index.jsx
  src/pages/pages.ts
Labels: Priority: Critical, Type: Enhancement
