Repository FC-final-project-team7/just-try-eat-ai-video-FE, pull requests merged in 2022-09, with the labels that each got.

#42 #11 Create Popup
  index.html
  src/components/Popup/NoticePopup/index.tsx
  src/components/Popup/PopupPortal.tsx
Labels: Priority: High, Type: Enhancement

#44 feat: Add GlobalStyle
  src/App.tsx
  src/styles/GlobalStyle.tsx
Labels: Priority: Critical, Type: Enhancement

#45 style: Apply BG-HTML
  src/styles/GlobalStyle.tsx
Labels: Priority: Critical, Type: Enhancement

#47 #13 feat: Create Project text API
  src/stores/apis/index.ts
  src/stores/apis/projectText.ts
  src/stores/apis/tags.ts
  src/stores/index.tsx
  src/types/projects.ts
Labels: Priority: Critical, Type: Enhancement

#48 #33 Create ProjectListContainer
  src/pages/ProjectListPage/Card/ProjectCard/index.tsx
  src/pages/ProjectListPage/Card/ProjectCard/style.ts
  src/pages/ProjectListPage/Card/VideoCard/index.tsx
  src/pages/ProjectListPage/ListContainer/ProjectList/index.tsx
  src/pages/ProjectListPage/ListContainer/ProjectList/style.ts
  src/pages/ProjectListPage/ListContainer/VideoList/index.tsx
  src/pages/ProjectListPage/data.ts
  src/pages/ProjectListPage/index.tsx
  src/pages/index.jsx
  src/types/projects.ts
Labels: Priority: Critical, Type: Enhancement

#49 feat: Add theme style
  src/components/Buttons/BaseButton.tsx
  src/styles/theme.ts
Labels: Priority: High

#50 feat: Add global font
  src/styles/GlobalStyle.tsx
Labels: Priority: High

#51 #9 feat: Apply Style and props
  .idea/jsLibraryMappings.xml
  src/components/Buttons/BaseButton.tsx
  src/components/Buttons/FilledButton/index.tsx
  src/components/Buttons/OutlinedButton/index.tsx
  src/pages/ProjectListPage/ListContainer/ProjectList/style.ts
  src/styles/theme.ts
Labels: Priority: Critical, Type: Enhancement

#52 #9 feat: Update ImageButton and Apply test page
  package.json
  src/components/Buttons/ImageButton/index.tsx
  src/pages/ComponentsDisplay/Buttons/index.tsx
  yarn.lock
Labels: Priority: Critical, Type: Enhancement

#54 #12 feat: Create Dummy ProjectTextPage
  src/pages/ProjectText/ProjectTextArea/index.tsx
  src/pages/ProjectText/ProjectTextStepper/index.tsx
  src/pages/ProjectText/ProjectVoiceOptions/index.tsx
  src/pages/ProjectText/ProjectVoiceSelect/index.tsx
  src/pages/ProjectText/index.tsx
  src/pages/index.jsx
Labels: Priority: Critical, Type: Enhancement

#56 style: Add reset
  src/styles/GlobalStyle.tsx
  src/styles/reset.ts
Labels: Priority: Low, Type: Enhancement

#57 #33 Update ProjectListContainer
  src/pages/ProjectListPage/ListContainer/ProjectList/style.ts
  src/pages/ProjectListPage/ListContainer/VideoList/style.ts
  src/pages/ProjectListPage/assets/dummy/video-card-thumbnail.png
Labels: Priority: Low
